version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: badoo-bot
    depends_on:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app:Z
    networks:
      - appnet

  redis-cache:
    image: docker.io/library/redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
